### ISSUE TITLE
您好，看了您的教程，收获良多，但是依然还有一处疑问

### ISSUE THREAD

**Issue by zjhch123** [git-onepixel/jdate#1]
在代码[94行](https://github.com/git-onepixel/jdate/blob/master/jdate.js#L94)
```
init.prototype = jDate.fn;
```
实际上应该是一个继承的思路对吗？那是否应该在后面续写一句
```
init.prototype.constructor = init;
```
之后就变为
```
init.prototype = jDate.fn;
init.prototype.constructor = init;
```
这样似乎会更规范一些？
我对这些概念的理解还不够透彻…希望博主能不吝赐教哈

**Comment by git-onepixel** [comment]
嗯，这是一个继承关系。
你说的对，应该再加一句 init.prototype.constructor = init; 
constructor一般是在重写prototype之后重新赋值的，以保证原有构造函数不被改变。

但constructor本身没有太大的作用，这是因为：

函数A被定义时，JS引擎会给A添加一个prototype, 然后再给prototype添加一个constructor属性，并让其指向A的引用。这样做的目的是，当函数A被作为构造函数用来创建对象时，new出来的实例对象obj 就保留了对A的引用，这样，obj对象就被标记为是“A”类型，使得创建的对象更加规范，有名有姓，可追溯。

**Comment by zjhch123** [comment]
多谢多谢…真的是受益匪浅
